### PR TITLE
Reformat the code and make a readme

### PR DESCRIPTION
**Pull request by tusharhero**
If you want changes in the read me tell me.

### CODE REVIEW

**Comment by gl-yziquel** [comment]
Use `black` to format code.

**Comment by gl-yziquel** [comment]
And `README.md` would do well to provide usage examples. So that people do not have to guess what the code is really doing.

**Comment by tusharhero** [comment]
> Use `black` to format code.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/SwastikMajumder/math_ai/pull/1#issuecomment-1857827475
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

I have reformatted the code with black in this PR. :D

**Comment by gl-yziquel** [comment]
I meant: use `black` in some `nox` thingy or whatever *gasp* **shock** *horror* packaging solution does it.

Doing it manually is fun. Doing it automatically is better.

**Comment by tusharhero** [comment]
a git hook would do?

**Comment by gl-yziquel** [comment]
Knock yourself out. But ask the author. I'm not the one to make decisions. Not my code.

And this discussion is essentially the outgrowth of some IRC food fight. So no biggie.

**Pull request merged**
